# Generated by Django 2.0.1 on 2018-07-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_info',
            field=models.TextField(default='This is the information!'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='training', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='course',
            name='course_teacher',
            field=models.CharField(default='hank', max_length=255),
        ),
    ]
